sudo: false
git:
  depth: 1
branches:
  only:
    - master
    - development
language: node_js
node_js:
  - 10
dist: xenial
services:
  - xvfb
before_install:
  # help Travis to use Chrome
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
